name: Build Kotsync Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.13

      - name: Clone Kotatsu SyncServer
        run: |
          git clone https://github.com/KotatsuApp/kotatsu-syncserver.git
          cd kotatsu-syncserver
          ./gradlew shadowJar
          mv build/libs/*.jar ../kotsync.jar

      - name: Configure Git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Delete old Kotsync release and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete Kotsync -y || true
          git push origin :refs/tags/Kotsync || true

      - name: Create new tag
        run: |
          git tag -a Kotsync -m "Latest Kotsync build"
          git push origin Kotsync --force

      - name: Create GitHub release (Kotsync)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create Kotsync "kotsync.jar" \
            --title "Kotsync - $GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER" \
            --notes "Auto-built Kotatsu SyncServer from https://github.com/KotatsuApp/kotatsu-syncserver\nBuild date: $(date '+%Y-%m-%d %H:%M:%S %Z')"
