name: Build Kernel A71 Android 16 Docker

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_samsung_a71
          kernel-branch: lineage-23.2
          config: a71_defconfig
          arch: arm64
          
          # HỖ TRỢ DOCKER
          lxc: true
          lxc-patch: true
          
          # TẮT TỰ ĐỘNG TẢI (VÌ ĐANG LỖI 400)
          aosp-clang: false
          aosp-gcc: false
          
          # DÙNG LINK TOOLCHAIN THỦ CÔNG (SỬ DỤNG CLANG 17+ CHO ANDROID 16)
          # Sử dụng Proton Clang hoặc Azure Clang - Rất ổn định cho Kernel Android
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master
          
          # DÙNG GCC ĐỂ MỒI (BUILD CHO ARM64)
          other-gcc64-url: https://github.com/mvaisakh/gcc-arm64.git
          other-gcc64-branch: master
          
          # DÙNG GCC CHO ARM32 (CẦN CHO CÁC MODULE WIFI/MẠNG)
          other-gcc32-url: https://github.com/mvaisakh/gcc-arm.git
          other-gcc32-branch: master
          
          android-version: 16
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
          # THÊM BIẾN ĐỂ ÉP BIÊN DỊCH BẰNG LLVM (CHỐNG LỖI)
          extra-make-args: '["LLVM=1", "LLVM_IAS=1"]'
