name: Build Stremio Service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl build-essential pkg-config musl-tools

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add x86_64-unknown-linux-musl

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Stremio/stremio-service
          path: src

      - name: Build static binary (musl)
        working-directory: src
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: |
          cargo build --release --target x86_64-unknown-linux-musl --features vendored

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: stremio-service-binary
          path: src/target/x86_64-unknown-linux-musl/release/stremio-service
